version: '3.8'

services:
  elasticsearch1:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.5
    container_name: elasticsearch1
    environment:
      - node.name=elasticsearch1
      - cluster.name=elastic-cluster
      - discovery.seed_hosts=elasticsearch2
      - cluster.initial_master_nodes=elasticsearch1,elasticsearch2
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 1g
    volumes:
      - ./es_data/es1:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    networks:
      - elk

  elasticsearch2:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.5
    container_name: elasticsearch2
    environment:
      - node.name=elasticsearch2
      - cluster.name=elastic-cluster
      - discovery.seed_hosts=elasticsearch1
      - cluster.initial_master_nodes=elasticsearch1,elasticsearch2
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 1g
    volumes:
      - ./es_data/es2:/usr/share/elasticsearch/data
    networks:
      - elk

  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.5
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch1:9200 # envir_variable 
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch1
      - elasticsearch2
    networks:
      - elk    

  logstash:
    image: docker.elastic.co/logstash/logstash:7.17.5
    container_name: logstash
    environment:
      - LS_JAVA_OPTS=-Xms1g -Xmx1g
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml
      - ./logstash/pipeline:/usr/share/logstash/pipeline
    ports:
      - "5044:5044"
      - "9600:9600"
    depends_on:
      - elasticsearch1
      - elasticsearch2
    networks:
      - elk 

  filebeat:
    image: docker.elastic.co/beats/filebeat:7.14.0
    container_name: filebeat
    volumes:
      - ./filebeat/filebeat.yaml:/usr/share/filebeat/filebeat.yaml:ro
      - ./btc_app/btc_val.log:/usr/share/filebeat/logs/btc_val.log:rw
    depends_on:
      - logstash
    networks:
      - elk

  grafana:
    image: grafana/grafana:latest
    container_name:  grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    ports:
      - 3000:3000
    volumes:
      - ./grafana/data:/var/lib/grafana
    depends_on:
      - elasticsearch1
      - elasticsearch2
    networks:
      - elk

networks:
  elk:
    driver: bridge

volumes:
  es_data:
